/** Entry constants without Zod — client editor components may import them. */

/** Max articles (chapters) per topic: two columns of tiles, six rows (DB allows 12). */
export const MAX_CHAPTERS = 12;

/** Max links in the "Learn more" tiles of one topic (DB `replace_entry_parts`). */
export const MAX_LINKS = 200;

/** Max "Learn more" tiles of one topic or template (DB `replace_tiles`). */
export const MAX_TILES = 24;

/** Shared preview validity periods in hours (the DB allows 1 to 720). */
export const PREVIEW_HOURS = [24, 72, 168, 720] as const;

/**
 * Icons a tile may use (142); the picture of each is in TileIcon.tsx. The
 * database only checks the shape of the name (`is_tile_icon`).
 */
export const TILE_ICONS = [
  "video",
  "podcast",
  "mic",
  "chart",
  "database",
  "map",
  "book",
  "news",
  "file",
  "pen",
  "quote",
  "graduation",
  "idea",
  "people",
  "landmark",
  "scale",
  "shield",
  "flag",
  "heart",
  "leaf",
  "calendar",
  "image",
  "globe",
  "link",
  "video-alt",
  "film",
  "tv",
  "radio",
  "headphones",
  "music",
  "camera",
  "images",
  "presentation",
  "monitor",
  "book-alt",
  "library",
  "book-marked",
  "notebook",
  "notebook-pen",
  "scroll-text",
  "file-spreadsheet",
  "file-bar-chart",
  "files",
  "clipboard-list",
  "chart-pie",
  "chart-line",
  "chart-bar",
  "trending-up",
  "trending-down",
  "sigma",
  "calculator",
  "percent",
  "table",
  "school",
  "university",
  "backpack",
  "pencil-ruler",
  "microscope",
  "flask-conical",
  "atom",
  "brain",
  "message-square",
  "messages-square",
  "message-circle",
  "mail",
  "megaphone",
  "speech",
  "languages",
  "earth",
  "map-pin",
  "compass",
  "navigation",
  "plane",
  "ship",
  "train",
  "car",
  "route",
  "mountain",
  "trees",
  "tree-pine",
  "sun",
  "cloud-rain",
  "snowflake",
  "flame",
  "droplets",
  "waves",
  "wind",
  "thermometer",
  "recycle",
  "factory",
  "zap",
  "fuel",
  "wheat",
  "apple",
  "utensils",
  "home",
  "building",
  "building2",
  "tent",
  "hospital",
  "stethoscope",
  "pill",
  "syringe",
  "baby",
  "accessibility",
  "hand-heart",
  "hand-coins",
  "coins",
  "banknote",
  "wallet",
  "piggy-bank",
  "briefcase",
  "gavel",
  "vote",
  "siren",
  "swords",
  "shield-alt",
  "lock",
  "fingerprint",
  "eye",
  "search",
  "info",
  "circle-help",
  "star",
  "award",
  "trophy",
  "target",
  "puzzle",
  "cpu",
  "smartphone",
  "wifi",
  "rss",
  "archive",
  "package",
  "handshake",
  "user-round",
  "users-round",
  "footprints",
  "anchor",
  "hourglass",
  "clock",
  "history",
] as const;
export type TileIcon = (typeof TILE_ICONS)[number];

/** A stored icon name → a known one ("link" for anything unexpected). */
export const toTileIcon = (value: string): TileIcon =>
  (TILE_ICONS as readonly string[]).includes(value) ? (value as TileIcon) : "link";

export const TILE_ICON_LABEL: Record<TileIcon, string> = {
  video: "Video",
  podcast: "Podcast",
  mic: "Lecture",
  chart: "Chart",
  database: "Data",
  map: "Map",
  book: "Book",
  news: "News",
  file: "Document",
  pen: "Notes",
  quote: "Quote",
  graduation: "Education",
  idea: "Idea",
  people: "People",
  landmark: "Institution",
  scale: "Law",
  shield: "Security",
  flag: "Country",
  heart: "Aid",
  leaf: "Environment",
  calendar: "Events",
  image: "Image",
  globe: "Globe",
  link: "Link",
  "video-alt": "Video",
  film: "Film",
  tv: "Tv",
  radio: "Radio",
  headphones: "Headphones",
  music: "Music",
  camera: "Camera",
  images: "Images",
  presentation: "Presentation",
  monitor: "Monitor",
  "book-alt": "Book",
  library: "Library",
  "book-marked": "Book Marked",
  notebook: "Notebook",
  "notebook-pen": "Notebook Pen",
  "scroll-text": "Scroll Text",
  "file-spreadsheet": "File Spreadsheet",
  "file-bar-chart": "File Bar Chart",
  files: "Files",
  "clipboard-list": "Clipboard List",
  "chart-pie": "Chart Pie",
  "chart-line": "Chart Line",
  "chart-bar": "Chart Bar",
  "trending-up": "Trending Up",
  "trending-down": "Trending Down",
  sigma: "Sigma",
  calculator: "Calculator",
  percent: "Percent",
  table: "Table",
  school: "School",
  university: "University",
  backpack: "Backpack",
  "pencil-ruler": "Pencil Ruler",
  microscope: "Microscope",
  "flask-conical": "Flask Conical",
  atom: "Atom",
  brain: "Brain",
  "message-square": "Message Square",
  "messages-square": "Messages Square",
  "message-circle": "Message Circle",
  mail: "Mail",
  megaphone: "Megaphone",
  speech: "Speech",
  languages: "Languages",
  earth: "Earth",
  "map-pin": "Map Pin",
  compass: "Compass",
  navigation: "Navigation",
  plane: "Plane",
  ship: "Ship",
  train: "Train",
  car: "Car",
  route: "Route",
  mountain: "Mountain",
  trees: "Trees",
  "tree-pine": "Tree Pine",
  sun: "Sun",
  "cloud-rain": "Cloud Rain",
  snowflake: "Snowflake",
  flame: "Flame",
  droplets: "Droplets",
  waves: "Waves",
  wind: "Wind",
  thermometer: "Thermometer",
  recycle: "Recycle",
  factory: "Factory",
  zap: "Zap",
  fuel: "Fuel",
  wheat: "Wheat",
  apple: "Apple",
  utensils: "Utensils",
  home: "Home",
  building: "Building",
  building2: "Building 2",
  tent: "Tent",
  hospital: "Hospital",
  stethoscope: "Stethoscope",
  pill: "Pill",
  syringe: "Syringe",
  baby: "Baby",
  accessibility: "Accessibility",
  "hand-heart": "Hand Heart",
  "hand-coins": "Hand Coins",
  coins: "Coins",
  banknote: "Banknote",
  wallet: "Wallet",
  "piggy-bank": "Piggy Bank",
  briefcase: "Briefcase",
  gavel: "Gavel",
  vote: "Vote",
  siren: "Siren",
  swords: "Swords",
  "shield-alt": "Shield",
  lock: "Lock",
  fingerprint: "Fingerprint",
  eye: "Eye",
  search: "Search",
  info: "Info",
  "circle-help": "Circle Help",
  star: "Star",
  award: "Award",
  trophy: "Trophy",
  target: "Target",
  puzzle: "Puzzle",
  cpu: "Cpu",
  smartphone: "Smartphone",
  wifi: "Wifi",
  rss: "Rss",
  archive: "Archive",
  package: "Package",
  handshake: "Handshake",
  "user-round": "User Round",
  "users-round": "Users Round",
  footprints: "Footprints",
  anchor: "Anchor",
  hourglass: "Hourglass",
  clock: "Clock",
  history: "History",
};

/** Globe layers a topic can be counted on (DB `entries.map_layers`). */
export const MAP_LAYERS = ["countries", "regions", "issues"] as const;
export type MapLayer = (typeof MAP_LAYERS)[number];

export const MAP_LAYER_LABEL: Record<MapLayer, string> = {
  countries: "Countries",
  regions: "Regions",
  issues: "Special regions",
};

/** Search engine limits for the SEO fields (DB checks on `entries`). */
export const SEO_TITLE_MAX = 70;
export const SEO_DESCRIPTION_MAX = 170;
export const GEO_SUMMARY_MAX = 800;
