import { PATRONS_EMAIL } from "@/features/membership/config";
import { SOCIALS } from "./navigation";

/**
 * Facts about the publisher, the single source for structured data
 * (Organization / NGO), llms.txt, feeds and the About page. Keep in sync
 * with the public register; the owner checks them (docs/seo-geo-audit.md).
 */
export const ORGANIZATION = {
  name: "Atlas of Today's World",
  alternateName: ["Atlas of Todays World", "ATW"],
  /** Registered association (spolek) under Czech law, renamed in 2026. */
  legalName: "Atlas of Today's World, z. s.",
  /** Czech company registration number (IČO). */
  companyId: "05363454",
  foundingDate: "2016-09-07",
  email: PATRONS_EMAIL,
  address: {
    streetAddress: "náměstí Jana Palacha 1/2",
    postalCode: "110 00",
    addressLocality: "Praha 1",
    addressCountry: "CZ",
  },
  description:
    "Atlas of Today's World is a non-profit, open-access encyclopedia of the present: every country, world region and global issue on an interactive 3D globe, with data from international sources and articles by experts.",
  /**
   * Same legal entity under its former name (Online Encyclopedia of Migration, z.s.;
   * IČO matches). Update when the Atlas gets its own Wikidata item.
   */
  wikidata: "https://www.wikidata.org/wiki/Q106194019",
  /** Square raster logo (Google wants ≥ 112 px), generated by app/logo.png. */
  logoPath: "/logo.png",
  logoSize: 512,
  socials: SOCIALS.map((social) => social.href),
} as const;
