/**
 * Registry of the map's data layers ("Encyclopedia view" / "HDI view" / ...).
 *
 * Adding another layer = one entry here + `npm run data:indicators`.
 * Nothing else needs editing – the legend, globe colouring, switcher and country
 * card are all generated from this metadata.
 *
 * `owidSlug` is the grapher name on ourworldindata.org (last part of the URL).
 * `valueColumn` is the CSV column name; if omitted, the 4th column is used.
 */
export const INDICATORS = [
  {
    id: "hdi",
    label: "Human Development Index",
    shortLabel: "HDI",
    owidSlug: "human-development-index",
    valueColumn: "hdi__sex_total",
    unit: "",
    decimals: 3,
    source: "United Nations Development Programme (UNDP)",
    sourceUrl: "https://hdr.undp.org/",
    type: "sequential",
    domain: [0.4, 0.96],
    // Light yellow (low) -> dark blue (high). Matches the HDI view in Figma.
    ramp: ["#F2F7C4", "#C7E9B4", "#7FCDBB", "#41B6C4", "#1D91C0", "#225EA8", "#0C2C84"],
    higherIsBetter: true,
  },
  {
    id: "life-expectancy",
    label: "Life expectancy at birth",
    shortLabel: "Life expectancy",
    owidSlug: "life-expectancy",
    unit: " yrs",
    decimals: 1,
    source: "UN World Population Prospects",
    sourceUrl: "https://population.un.org/wpp/",
    type: "sequential",
    domain: [52, 86],
    ramp: ["#FFF3D6", "#FBD9A5", "#F3A66C", "#D97757", "#A8452F", "#6E2318", "#3D1209"],
    higherIsBetter: true,
  },
  {
    id: "gdp-per-capita",
    label: "GDP per capita (PPP, int-$)",
    shortLabel: "GDP per capita",
    owidSlug: "gdp-per-capita-worldbank",
    unit: " $",
    decimals: 0,
    source: "World Bank",
    sourceUrl: "https://data.worldbank.org/",
    type: "sequential",
    scale: "log",
    domain: [800, 90000],
    ramp: ["#EDF8E9", "#C7E9C0", "#A1D99B", "#74C476", "#41AB5D", "#238B45", "#005A32"],
    higherIsBetter: true,
  },
  {
    id: "political-regime",
    label: "Political regime",
    shortLabel: "Political regime",
    owidSlug: "political-regime",
    unit: "",
    decimals: 0,
    source: "V-Dem (Regimes of the World), via Our World in Data",
    sourceUrl: "https://ourworldindata.org/grapher/political-regime",
    type: "categorical",
    categories: [
      { value: 0, label: "Closed autocracy", color: "#8C2F39" },
      { value: 1, label: "Electoral autocracy", color: "#D98E5A" },
      { value: 2, label: "Electoral democracy", color: "#7FB3D5" },
      { value: 3, label: "Liberal democracy", color: "#1F4E8C" },
    ],
    higherIsBetter: true,
  },
  {
    id: "democracy-index",
    label: "Electoral democracy index",
    shortLabel: "Democracy",
    owidSlug: "electoral-democracy-index",
    unit: "",
    decimals: 2,
    source: "V-Dem, via Our World in Data",
    sourceUrl: "https://ourworldindata.org/grapher/electoral-democracy-index",
    type: "sequential",
    domain: [0.05, 0.92],
    ramp: ["#7A1F2B", "#B4534A", "#D89A73", "#E8D5A8", "#9CC3D9", "#4A7FB5", "#1B3F73"],
    higherIsBetter: true,
  },
  {
    id: "corruption",
    label: "Corruption Perceptions Index",
    shortLabel: "Corruption",
    owidSlug: "ti-corruption-perception-index",
    unit: "/100",
    decimals: 0,
    source: "Transparency International",
    sourceUrl: "https://www.transparency.org/en/cpi",
    type: "sequential",
    domain: [10, 90],
    ramp: ["#6B1F2E", "#A3463F", "#CE7E5C", "#E5BE8C", "#A9C9A4", "#5E9E76", "#26654B"],
    higherIsBetter: true,
  },
  {
    id: "extreme-poverty",
    label: "Population in extreme poverty",
    shortLabel: "Extreme poverty",
    owidSlug: "share-of-population-in-extreme-poverty",
    unit: " %",
    decimals: 1,
    source: "World Bank Poverty and Inequality Platform",
    sourceUrl: "https://pip.worldbank.org/",
    type: "sequential",
    domain: [0, 70],
    ramp: ["#F7F4F9", "#E7E1EF", "#D4B9DA", "#C994C7", "#DF65B0", "#DD1C77", "#980043"],
    higherIsBetter: false,
  },
  {
    id: "co2-per-capita",
    label: "CO₂ emissions per capita",
    shortLabel: "CO₂ per capita",
    owidSlug: "co-emissions-per-capita",
    unit: " t",
    decimals: 1,
    source: "Global Carbon Budget",
    sourceUrl: "https://globalcarbonbudget.org/",
    type: "sequential",
    domain: [0, 20],
    ramp: ["#F0F4F5", "#D3DEE3", "#A9BEC9", "#7D97A8", "#556E82", "#34485B", "#1B2836"],
    higherIsBetter: false,
  },
  {
    id: "internet-users",
    label: "Share of population using the internet",
    shortLabel: "Internet users",
    owidSlug: "share-of-individuals-using-the-internet",
    unit: " %",
    decimals: 1,
    source: "International Telecommunication Union (ITU)",
    sourceUrl: "https://www.itu.int/",
    type: "sequential",
    domain: [5, 99],
    ramp: ["#F7FBFF", "#D6E6F4", "#AECFE8", "#7BB0D8", "#4A8CC2", "#2A66A3", "#123F73"],
    higherIsBetter: true,
  },
];
