import {
  Accessibility,
  Anchor,
  Apple,
  Archive,
  Atom,
  Award,
  Baby,
  Backpack,
  Banknote,
  Book,
  BookMarked,
  BookOpen,
  Brain,
  Briefcase,
  Building,
  Building2,
  Calculator,
  CalendarDays,
  Camera,
  Car,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartPie,
  CircleHelp,
  Clapperboard,
  ClipboardList,
  Clock,
  CloudRain,
  Coins,
  Compass,
  Cpu,
  Database,
  Droplets,
  Earth,
  Eye,
  Factory,
  FileBarChart,
  FileSpreadsheet,
  FileText,
  Files,
  Film,
  Fingerprint,
  Flag,
  Flame,
  FlaskConical,
  Footprints,
  Fuel,
  Gavel,
  Globe,
  GraduationCap,
  HandCoins,
  HandHeart,
  Handshake,
  Headphones,
  HeartHandshake,
  History,
  Home,
  Hospital,
  Hourglass,
  Image as ImageIcon,
  Images,
  Info,
  Landmark,
  Languages,
  Leaf,
  Library,
  Lightbulb,
  Link as LinkIcon,
  Lock,
  Mail,
  Map as MapIcon,
  MapPin,
  Megaphone,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Microscope,
  Monitor,
  Mountain,
  Music,
  Navigation,
  Newspaper,
  Notebook,
  NotebookPen,
  Package,
  PenLine,
  PencilRuler,
  Percent,
  PiggyBank,
  Pill,
  Plane,
  Podcast,
  Presentation,
  Puzzle,
  Quote,
  Radio,
  Recycle,
  Route,
  Rss,
  Scale,
  School,
  ScrollText,
  Search,
  Shield,
  ShieldCheck,
  Ship,
  Sigma,
  Siren,
  Smartphone,
  Snowflake,
  Speech,
  Star,
  Stethoscope,
  Sun,
  Swords,
  Syringe,
  Table,
  Target,
  Tent,
  Thermometer,
  Train,
  TreePine,
  Trees,
  TrendingDown,
  TrendingUp,
  Trophy,
  Tv,
  University,
  UserRound,
  Users,
  UsersRound,
  Utensils,
  Video,
  Vote,
  Wallet,
  Waves,
  Wheat,
  Wifi,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { toTileIcon, type TileIcon as TileIconName } from "../constants";

const ICONS: Record<TileIconName, LucideIcon> = {
  video: Clapperboard,
  podcast: Podcast,
  mic: Mic,
  chart: ChartColumn,
  database: Database,
  map: MapIcon,
  book: BookOpen,
  news: Newspaper,
  file: FileText,
  pen: PenLine,
  quote: Quote,
  graduation: GraduationCap,
  idea: Lightbulb,
  people: Users,
  landmark: Landmark,
  scale: Scale,
  shield: ShieldCheck,
  flag: Flag,
  heart: HeartHandshake,
  leaf: Leaf,
  calendar: CalendarDays,
  image: ImageIcon,
  globe: Globe,
  link: LinkIcon,
  "video-alt": Video,
  film: Film,
  tv: Tv,
  radio: Radio,
  headphones: Headphones,
  music: Music,
  camera: Camera,
  images: Images,
  presentation: Presentation,
  monitor: Monitor,
  "book-alt": Book,
  library: Library,
  "book-marked": BookMarked,
  notebook: Notebook,
  "notebook-pen": NotebookPen,
  "scroll-text": ScrollText,
  "file-spreadsheet": FileSpreadsheet,
  "file-bar-chart": FileBarChart,
  files: Files,
  "clipboard-list": ClipboardList,
  "chart-pie": ChartPie,
  "chart-line": ChartLine,
  "chart-bar": ChartBar,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  sigma: Sigma,
  calculator: Calculator,
  percent: Percent,
  table: Table,
  school: School,
  university: University,
  backpack: Backpack,
  "pencil-ruler": PencilRuler,
  microscope: Microscope,
  "flask-conical": FlaskConical,
  atom: Atom,
  brain: Brain,
  "message-square": MessageSquare,
  "messages-square": MessagesSquare,
  "message-circle": MessageCircle,
  mail: Mail,
  megaphone: Megaphone,
  speech: Speech,
  languages: Languages,
  earth: Earth,
  "map-pin": MapPin,
  compass: Compass,
  navigation: Navigation,
  plane: Plane,
  ship: Ship,
  train: Train,
  car: Car,
  route: Route,
  mountain: Mountain,
  trees: Trees,
  "tree-pine": TreePine,
  sun: Sun,
  "cloud-rain": CloudRain,
  snowflake: Snowflake,
  flame: Flame,
  droplets: Droplets,
  waves: Waves,
  wind: Wind,
  thermometer: Thermometer,
  recycle: Recycle,
  factory: Factory,
  zap: Zap,
  fuel: Fuel,
  wheat: Wheat,
  apple: Apple,
  utensils: Utensils,
  home: Home,
  building: Building,
  building2: Building2,
  tent: Tent,
  hospital: Hospital,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  baby: Baby,
  accessibility: Accessibility,
  "hand-heart": HandHeart,
  "hand-coins": HandCoins,
  coins: Coins,
  banknote: Banknote,
  wallet: Wallet,
  "piggy-bank": PiggyBank,
  briefcase: Briefcase,
  gavel: Gavel,
  vote: Vote,
  siren: Siren,
  swords: Swords,
  "shield-alt": Shield,
  lock: Lock,
  fingerprint: Fingerprint,
  eye: Eye,
  search: Search,
  info: Info,
  "circle-help": CircleHelp,
  star: Star,
  award: Award,
  trophy: Trophy,
  target: Target,
  puzzle: Puzzle,
  cpu: Cpu,
  smartphone: Smartphone,
  wifi: Wifi,
  rss: Rss,
  archive: Archive,
  package: Package,
  handshake: Handshake,
  "user-round": UserRound,
  "users-round": UsersRound,
  footprints: Footprints,
  anchor: Anchor,
  hourglass: Hourglass,
  clock: Clock,
  history: History,
};

/** The picture of a tile icon (public tiles and the admin picker share it). */
export function TileIcon({ name, className }: { name: string; className?: string }) {
  const Icon = ICONS[toTileIcon(name)];
  return <Icon aria-hidden className={className} />;
}
